services:
  Dbp\Relay\GreenlightBundle\Command\CleanupCommand:
    autowire: true
    autoconfigure: true

#  Dbp\Relay\GreenlightBundle\Controller\:
#    resource: '../../Controller'
#    tags: ['controller.service_arguments']
#    autowire: true

  Dbp\Relay\GreenlightBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\GreenlightBundle\DataProvider\PermitCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

  Dbp\Relay\GreenlightBundle\DataProvider\PermitItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true

  Dbp\Relay\GreenlightBundle\Service\GreenlightService:
    autowire: true
    autoconfigure: true
